name: madek_v3/integration-tests
windows:
  '2':
    name: "ApacheHTTPd"
    command: |
      while true; do
        LD_LIBRARY_PATH=/opt/local/lib/apache2/modules/ \
          /opt/local/sbin/apachectl -d reverse-proxy -e info -DFOREGROUND
        sleep 1;
      done
  '7':
    name: test
    command: bundle exec rspec spec
