name: MADEK/madek/integration-tests
windows:
  3:
    name: apache2
    command: |
      while true; do
        rm -rf logs/*
        DYLD_LIBRARY_PATH=/opt/local/lib/apache2/modules/  \
          /opt/local/sbin/httpd -d reverse-proxy -f conf/httpd.conf -e info -DFOREGROUND
        sleep 1
      done
  7:
    name: test
    command: bundle exec rspec spec
