source 'https://rubygems.org'

gem 'activesupport'
gem 'addressable'
gem 'capybara', '~> 3.8'
gem 'factory_bot'
gem 'faker'
gem 'faraday'
gem 'geckodriver-helper'
gem 'git'
gem 'json_roa-client', '>= 1.0.0', '< 2.0.0'
gem 'mail'
gem 'nrepl', git: 'https://github.com/nullstyle/nrepl.git', ref: '3277748335e77ddeddaf4fb91b756ed4d40bc5a8'
gem 'pg'
gem 'pg-hstore', '~> 1.2'
gem 'post_office'
gem 'pry'
gem 'rest-client'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'sequel'
gem 'uuidtools'
