{{RAILS_ENV}}:
  adapter: postgresql
  host: localhost
  port: REPLACE_WITH_PGPORT
  pool: 3
  max_pool_size: 3
  timeout: 30000
  encoding: unicode
  username: REPLACE_WITH_PGUSER
  password: REPLACE_WITH_PGPASSWORD
  database: {{DATABASE}}
