create-database:
  body: |
    #!/usr/bin/env bash
    set -eux
    cd webapp/datalayer
    createdb "${DATABASE_NAME}"
    psql -d "${DATABASE_NAME}" -f db/structure.sql
    pg_restore --disable-triggers --exit-on-error -a -x -O -d "${DATABASE_NAME}" db/personas.pgbin

delete-database:
  body: |
    set -eux
    cd webapp
    dropdb "${DATABASE_NAME}"
  ignore-state: true
  ignore-abort: true
  start-when:
    - script: run-api
      states: [aborted, passed, failed, skipped]
    - script: run-webapp
      states: [aborted, passed, failed, skipped]
