create-database:
  body: |
    set -eux
    cd webapp/engines/datalayer
    bundle exec rake db:reset
    bundle exec rake db:pg:data:restore FILE=db/personas.pgbin
  start-when:
  - script: webapp-bundle-mri

delete-database:
  body: |
    set -eux
    cd webapp
    bundle exec rake db:pg:terminate_connections db:drop
  ignore-state: true
  ignore-abort: true
  start-when:
    - script: run-api
      states: [aborted, passed, failed, skipped]
    - script: run-webapp
      states: [aborted, passed, failed, skipped]
